# src/main/resources/application.yml
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: DiunOGej40FiEhiKtY3fpXVaxrzKbPTZ
            client-secret: hKgpgEfl0i2be3WyYf4fBQ14jCA5ukTwbMVWzsEQey5krtg2LtuFi_bqcNGv-eGg
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-ldlso580.us.auth0.com/